### ISSUE TITLE
Conflicting rules: Return undefined as last statement in computed

### ISSUE THREAD

**Issue by djfhe** [clickbar/eslint-config#14]
I can't return undefined
<img width="588" alt="image" src="https://user-images.githubusercontent.com/44621469/187205938-9e033372-8486-4c90-bb06-80faf1aea1d6.png">

But i also can't return undefined
<img width="695" alt="image" src="https://user-images.githubusercontent.com/44621469/187206040-6d85abc6-037f-4aa3-8b33-608be7f38ef5.png">

**Comment by studnitz** [comment]
We should disable `unicorn/no-useless-undefined` then, I think.

**Comment by studnitz** [comment]
Fixed
