### ISSUE TITLE
Conflicting rules unicorn/prevent-abbreviations and vue/require-macro-variable-name

### ISSUE THREAD

**Issue by Jidbo** [clickbar/eslint-config#20]
When using `useAttrs()` the rule `vue/require-macro-variable-name` requires the variable to be named `attrs` but `unicorn/prevent-abbreviations` requires that short names like `attrs` are written out in full length e.g. `attributes`

**Comment by studnitz** [comment]
Fixed in 3923659f72b22074d949885141398f30df9f044f and released in v5.0.4
